### PR TITLE
Changed Gun icon to Shield icon on proposed team

### PR DESCRIPTION
**Pull request by jezznar**
* Modified lobby.ejs: changed all gun.png lines to shield.png
* Modified lobby9.ejs: repositioned top coordinates of shield.png

Addresses issue #8

Cleaner view, imho.
test

### CODE REVIEW

**Comment by vck3000** [comment]
Thanks so much for this! Just a quick question, anything wrong with capital G in "drawGuns"?

**Comment by jezznar** [comment]
@vck3000 ahh, good that you noticed it, I did a replace all and forgot previous camel case.

**Comment by vck3000** [comment]
untitled

My local server isn't getting the shields to show up in the correct spot :(

**Comment by vck3000** [comment]
scrollshields

Looks like the positions of the shields aren't fixed as you change the height of the avatar play area. (Horizontal resizing is good). Would you like me to give it a shot? Or are you ok? Also team leader star is positioned there usually, any issues with them overlapping?

**Comment by jezznar** [comment]
It is definitely an issue because it should be visible at all times. Can you teach how you'd do it?

**Comment by jezznar** [comment]
@vck3000 Check this out?
test

**Comment by vck3000** [comment]
It looks like the shields don't reset their position back to the center like the guns did. Could you look into this? Guns are supposed to animate from the center of the play area, out to each player. Right now after the first pick, it will move from the last player the shield was at, to the new player with the shield.

How to reproduce:
- Start a game
- Pick a set of players
- Pick another set of players after previous one was rejected

Actual result:
- Guns move from old players to new players

Expected:
- Guns move from the center of the play area to the new players.

**Pull request closed without merging**
