### PR TITLE
made the whole thread-bubble clickable, closes #59

### LINKED ISSUE #59: In Forums, make the whole thread-bubble clickable, not just the title

### PR DESCRIPTION
**Pull request by hapr05**

### CODE REVIEW

**Comment by vck3000** [comment]
Looks good! Let me test when I'm home before merging.

**Comment by vck3000** [comment]
By the way if you have a discord let me know! I'll add you to the dev team chat!

**Comment by hapr05** [comment]
thanks, my discord username is tukangcendol

**Comment by vck3000** [comment]
Need your ID as well! Or you can add me: pkvk9122#6596

**Pull request merged**
