### PR TITLE
adding eslint to enforce code style

### PR DESCRIPTION
**Pull request by piguyinthesky**
I used [eslint](https://eslint.org/) to fix the code style in the entire project, except for the files under `assets/libraries`. I tried to guess what rules to use based on what the files already looked like:

- 4 spaces for indent
- double quotes
- each statement should be followed by a semicolon.

The rules are specified in `.eslintrc.json` in the base directory.

It shouldn't make any differences in the logic of the game itself, just the style of the code.

If this looks ok, I'll add a section to the readme on how to lint: you just run `npm run lint`, a script I wrote into `package.json`, into your terminal. We could also automatically lint before commits by setting
```
"scripts": {
    ...
    precommit: "npm run lint"
}
```

### CODE REVIEW

**Comment by vck3000** [comment]
The changes look good! Maybe you could have not ran it on the assets folder, but that's fine because it isn't a npm module that people install separately. They are downloaded with the source code. 

Please write in the readme on how to lint :). The precommit linting sounds ok. I worry that it may cause some unwanted changes to a user's code, but if we find it to cause extra trouble, we can disable it later. Please add that in too!

**Comment by piguyinthesky** [comment]
Alright, I added a little section to the readme and set ESLint to ignore the files in the `assets` directory. I also got rid of the precommit linting since it was preventing me from actually committing, since ESLint throws an error if it catches any problems.

**Comment by piguyinthesky** [comment]
Ok, I changed the classes and cards to follow ES6 class syntax! Hopefully, it's a little more straightforward than the code we had before. I changed all of the `var`s to `let`s and caught some variables that were somehow working without being declared.

**Comment by vck3000** [comment]
Thank you! I will review this when I return in a couple days sorry.

**Comment by vck3000** [comment]
I'm currently reviewing this and there's actually a lot of changes... I do have some worries:

1) Could you undo the ` redundant "=== true" checks ` and `replaced redundant !== true, etc. with negation operator 5bf9854 `commits? I would prefer if it was explicitly written out. 

2) Could you also undo the deletion of file `gameplay/anon.js` in commit `10eeebeccbeebf2400f54bf3033573dc85272795`? This was a work in progress for anonymous mode.

3) Could you also undo the deletion of the template.txt files? (Or update them to better fit your new ES6 style?)

There's still a lot I haven't seen, I will need more time to fully read this! It might be a good idea to do a voice call so you could walk your code through for me, but let me first read it through.

**Comment by vck3000** [comment]
It also looks like the roles are inheriting phases, could you explain to me why you did this? I built the game.js file to integrate the classes and phases together there, not to have the classes inherit phase data. (Maybe I need to start learning ES6 classes?)

**Comment by piguyinthesky** [comment]
Oops yeah, I kind of did a lot more than I was originally going to! I'll slow down and make a separate PR for all of the changes so we can go through them one at a time instead of this whole mess, lol. Sorry about that!

Another issue I was going to raise is that work-in-progress stuff shouldn't be in the `master` branch. Everything in the master branch should be ready for the public to use. I noticed some routes such as `/testmodal` are also available [on the public website](https://www.proavalon.com/testmodal), which I don't think should be happening.

We could solve this using a better [Git workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), i.e. a "develop" branch where we can test out changes.

Sorry if I'm overstepping a bit -- I know this isn't my project but I'm a bit of a perfectionist! I'll tag the separate pull requests here, thanks for your patience.

**Comment by vck3000** [comment]
I'm really grateful you're putting so much into this site! I appreciate it. I'm just a bit overwhelmed with a lot of my own life right now. Coding is less than a 1/4 of my studies (I study Engineering + Physics on top of my CS major), and it's hard to keep updated in so many different fields. 

I agree with a lot you say, but the main goal for me during development of this site was rapid development (speed) over quality. I had limited time to get this project up and running. Of course, now that the site is stable and has been up for (almost) more than a year, the site can focus more on quality and bringing things up to scratch! 

I like how you say you're a perfectionist because it helps teach me good practises and brings up the code quality of this project, which I just don't have the time and resources to fully maintain alone! I'm just a bit overwhelmed with all the changes right now - I want to make sure I still fully understand what's going on...! Thank you!

**Pull request closed without merging**
