### PR TITLE
Add term glossary that adds abbr

### PR DESCRIPTION
**Pull request by richardscollin**
Add NyanCat's proavalon glossary into the chat UI.

I tried getting a screenshot but couldn't take it while also hovering on my machine.

For now it is enabled for all players. I didn't want to bother going to the effort of selectively enabling it until I get approval about the current implementation.

There are a couple troublesome terms that I didn't add because they will cause issues with the current regex implementation. Particularly terms like m1.5 m2.3, etc. There are two main issues the period is treated as a word boundary so the regex that matches the shortest word will be shadowed by m1, etc.

That said using terms like 1.5 are pretty common in chat so maybe it would be still be worth implementing.

As for the usage in real life I copied a spectated chat log from the server currently and there were a lot of  terms that were highlighted. Maybe we should remove some entries to reduce clutter. I think terms that the standard English is equivalent to the Avalon definition we should maybe consider removing. I already did this for some definitions like team, but I think there are still some more.

Because this feature can make the chat UI a bit visually noisy I would like to add a chat command to selectively enable / disable this feature. We could then disable it for existing users and new users can have it enabled when they create an account.

Finally attribution. I think it would be good to attribute the definitions to NyanCat in some way. If you can think of a good way to include it in the UI let me know. Maybe when / if we add a chat command to selectively enable / disable this feature we can add a blurb there attributing him.

### CODE REVIEW

**Comment by richardscollin** [comment]
#372

**Comment by vck3000** [comment]
Very nice PR. Mods like this current implementation. This should definitely be a toggle-able option as you mentioned, either through the settings menu or through a chat command. 

I think the styling could do a bit of work. Some CSS and maybe our own custom "tooltip" could make it more responsive and look nicer too. 

I think it would be worth adding m2.3 or m4.5 definitions in. It could probably be done by extending `hasDefinition()` and `getDefinition()`. 

Overall, it looks really solid. Let me know if you aren't interested in styling it and I can merge this in now. We can work on styling it later.

**Comment by richardscollin** [comment]
Cool. Wait on the merge I have a couple changes I'd like to make. I'm adding a couple more definitions including the 1.1, 1.4, etc. just not m1.1 because of how it would have to be implemented. I think most people just type 1.1 and such in chat anyway and not m1.1

**Comment by richardscollin** [comment]
In response to your last comment, I'm not that interested in styling. It's good to merge whenever you want now. If I have some time next week I can work on an option for selectively enabling/disabling. I may also add more definitions as I see them being used in chat.

**Comment by vck3000** [comment]
Awesome. I noticed `mord`/`mordred`, `obe`/`oberon`, `rej`/`reject`, `pickrej`/`pickreject` and `merl`/`merlin` could also be made into aliases. Once those changes are up we can merge this in :).

**Pull request merged**
