### PR TITLE
Highlight picks in the current mission, and outline leader

### PR DESCRIPTION
**Pull request by NiharS**
This commit adds the ability to highlight previous picks in this mission by hovering over the pick dots, and also changes the highlighting of players to add a border around the leader of the mission.

### CODE REVIEW

**Comment by vck3000** [comment]
Sorry it took me so long to review this. It looks great except for one small thing... On hover, the avatars shrink a bit for both the missionBox and the pickbox hovers. Can you fix this?

**Comment by NiharS** [comment]
Thanks for the review! Good catch, didn't notice that. I wanted a border-like property in case people have hard time distinguishing color differences from leader being highlighted differently, since that might make it look like 4 people went on a 3 person mission if the leader didn't pick themselves. I switched to a box shadow as that won't change the inner element width. I hope this is okay! Thanks again for the review, and let me know if you think I should change it

**Comment by vck3000** [comment]
Looks great! What is your in game username so I can add you to the logs?

**Comment by NiharS** [comment]
Thanks! My in game username is Kneehar

**Pull request merged**
