### PR TITLE
Colorize game tables

### LINKED ISSUE #44: Colorize Game Tables in Lobby for different statuses
Colorize Game Tables in Lobby for different statuses, such that they are shaded a different color for each of {waiting, running, finished}.

### PR DESCRIPTION
**Pull request by piguyinthesky**
I added colours to the game tables in the lobby by basically adding a class to each `<td>` based off of the game's status, and then setting a `background-color` for that class in `assets/stylesheets/lobby.css`.

I used `lightblue` for `Frozen`, `lightyellow` for `Game in progress` and `lightgreen` for `Finished`. 

I can clean up the debug messages, if that matters. I also changed the long string concatenation to a template string that looks a bit neater.

Finally, I used jQuery to listen for the click event just so that it's a bit more consistent.

closes #44

### CODE REVIEW

**Comment by vck3000** [comment]
Looks good! Just need to test it.

**Comment by vck3000** [comment]
Seems like this doesn't work under dark theme. Would you mind checking into it? I had a lot of trouble getting the overriding dark theme to take priority. I remember I had to use a lot of `!important` in the CSS.

**Comment by CottageInTheCity** [comment]
Howdy howdy let's get ROWDY.

So I decided to expand from 3 colours to 5, and find a reasonable colour for both light mode (above) and dark mode (below)

**green for games that have not yet begun:**
#c8f5c8
#4e734e

**magenta for ongoing games:**
#f5c8f5 
#734e73

**blue for games that end in a res victory:** 
#c8c8f5 
#4e4e73

**red for games that end in a spy victory:**
#f5c8c8 
#734e4e

**grey for games that are frozen:** 
#f5f5f5
#737373

anyone with a keen eye may notice that there's a very deliberate pattern among these codes, to maintain a consistent feel across all colours and make it feel a bit more professional. you can see some examples for the colours in light mode [here](https://cdn.discordapp.com/attachments/265690325668855808/598825529298386944/unknown.png), [here](https://cdn.discordapp.com/attachments/265690325668855808/598825578228875274/unknown.png), [here](https://cdn.discordapp.com/attachments/265690325668855808/598825610491723786/unknown.png) and [here](https://cdn.discordapp.com/attachments/265690325668855808/598832470858661908/unknown.png). Please note that the third link showcases ongoing games as a pale yellow, however this didn't fit well on dark mode so I changed it to magenta (as showcased in the final light mode screenshot). you can find the screenshots for the colours on dark mode [here](https://cdn.discordapp.com/attachments/265690325668855808/598837390492303410/unknown.png), [here](https://cdn.discordapp.com/attachments/265690325668855808/598837410335424542/unknown.png) and [here](https://cdn.discordapp.com/attachments/265690325668855808/598837429151072257/unknown.png). Feel free to ask any questions or add anything to this xx

**Comment by CottageInTheCity** [comment]
Okay so I had a new idea, instead of changing the colours of the backgrounds (which will look kinda weird), we should change the colour of the text.

[Waiting For Game to Begin](https://cdn.discordapp.com/attachments/265690325668855808/600981805255884811/unknown.png)

[Game Currently In Progress](https://cdn.discordapp.com/attachments/265690325668855808/600982959826403341/unknown.png)

[Game Following Res Victory](https://cdn.discordapp.com/attachments/265690325668855808/600984051427573760/unknown.png)

[Game Following Spy Victory](https://cdn.discordapp.com/attachments/265690325668855808/600984115482722314/unknown.png)

Not sure how much of the text should be coloured, but here's some hexes I'd propose:

**light mode:**

waiting - #20ee20
ongoing - #eeee20 (yellow version)
res win - #2020ee
spy win - #ee2020
frozen - #202020

**dark mode:**

waiting - #57e857
ongoing - #e8e857 (yellow version)
res win - #5757e8
spy win - #e85757
frozen - #575757

**Comment by vck3000** [comment]
Closing due to inactivity.

**Pull request closed without merging**
