### PR TITLE
Install and run eslint to improve code style

### PR DESCRIPTION
**Pull request by piguyinthesky**
Ok here's **ANOTHER** (sigh) copy of #211 lol
I basically ran eslint to improve the style of the code so that it's hopefully better and more maintainable in the future.
However, since there are exceptions such as variables that are mutated in other files, this might cause some breaking changes.

### CODE REVIEW

**Comment by vck3000** [comment]
Two space tabs? :O

**Comment by piguyinthesky** [comment]
> Two space tabs? :O

Oops, I should have fixed it!

I'm not sure if there are any more of those errors caused by mutation in different files, I'll see if I can check for that using a regexp or something, but otherwise this should be fine.

**Comment by piguyinthesky** [comment]
Ok I was able to check for 'is not defined' errors via eslint. For future reference if we want to work on modularizing the code, the problem (shared across files) variables are:

```
[
  'assert',
  '$',
  'xmlhttp',
  'swal',
  'isSpectator',
  'gameStarted',
  'socket',
  'enableDisableButtons',
  'roomPlayersData',
  'ownUsername',
  'gameData',
  'roomId',
  'getOptions',
  'getHighlightedAvatars',
  'draw',
  'getKickPlayers',
  'changeView',
  'resetAllGameData',
  'inRoom',
  'showDangerAlert',
  'checkMessageForCommands',
  'scrollDown',
  'linkifyHtml',
  'selectedChat',
  'oldSpectators',
  'getIndexFromUsername',
  'docCookies',
  'mutedPlayers',
  'extendTabContentToBottomInRoom',
  'updateDarkTheme',
  'updateTwoTabs',
  'getUsernameFromIndex',
  'pics',
  'adjustGunPositions',
  'icons',
  'playerRatio',
  'assignCommands',
  'lastChatBoxCommand',
  'addToAllChat',
  'addToRoomChat',
  'isPlayerMuted',
  'playSound',
  'displayNotification',
  'username',
  'Swal',
  'drawVoteHistory',
  'serverLastUpdateDate',
  'autoCompleteStrs',
  'oldData',
  'infoIconString',
  'leaveRoom',
  'io',
  'checkStatusBarWithHeight',
  'runPublicDataAvalon',
  'setStatusBarText',
  'currentOptions',
  'widthOfRoom',
  'chatBox',
  'numPlayersOnMission',
  'print_gameplay_text_game_started',
  'print_gameplay_text_picked_team',
  'print_gameplay_text_vote_results',
  'print_last_mission_num',
  'oldProposedTeam',
  'arrayMessage',
  'messageCommand',
  'modCommands',
  'adminCommands',
  'gameTableHeight',
  'myObj',
  'classStr',
  'numOfPlayers',
  'socketUsername',
  'data',
  'socketOfTarget',
  'index',
  'botsToRemove',
  'hostSock',
  'admins',
  'createNotifObj',
  'notificationVar',
  'forumId',
  'commentId',
  'replyId',
  'isMod',
  'logsObj',
  'stringsArray',
  'linkStr',
  'clientStatsData',
  'currentModActions',
  'dataObj',
  'returnVar',
  'messageToClient',
  'ioGlobal',
  'cutOffDate',
  'matchedIpsUsernames'
]
```

For now, I'll go through these and change the `const`s to `let`s, but if something is used in multiple files we could probably define them in a master "index" file or something like that. That, or we start using bundlers like webpack... which would probably not be worth the effort

**Comment by vck3000** [comment]
Hmmm, could you fix up the merge conflicts please? I'll try to merge in the PR asap so that we can move onward. I'm thinking about putting in a bundler actually. I haven't fully thought out the full process, but I am thinking towards that as the next step in addition to ESLint. 

I was also thinking about starting to sprinkle in some React components. I'll have to see how much time I have in the near future.

**Comment by vck3000** [comment]
The code changes break the server code... Could you please confirm that you can start it normally? If it's too much you don't have to complete this PR.

**Comment by piguyinthesky** [comment]
I think what happened is that there were more recent changes in the master branch, so for those 4 files in the last commit, I just accepted all of the current changes (i.e. from the master branch).

**Pull request merged**
