### PR TITLE
relocated styles and made dark mode via footer

### PR DESCRIPTION
**Pull request by piguyinthesky**
Alright, so I started working on making the dark mode site-wide just by checking (via a script in the footer) if `"optionDisplayDarkTheme"` is stored in the browser's cookies, but only if we're not in the lobby, since it's already implemented there.

I moved all of the dark themes to a single file so it'll be easier to make sure our colors and stuff are consistent.

Now we just need to work on adding styles to make the dark mode actually, y'know, look ok.

### CODE REVIEW

**Comment by vck3000** [comment]
Code changes look pretty good! I will test this tonight and call upon the graphic designer to come up with some nice colours if needed!

**Comment by piguyinthesky** [comment]
Have we considered upgrading to Bootstrap 4, by the way? I think a lot of the css could be shortened by using the built-in bootstrap classes, and we could [also actually have a color theme](https://getbootstrap.com/docs/4.3/getting-started/theming/) instead of manually typing in hex codes each time. It'd be easier to spread the themes across the whole site, as well.

**Comment by piguyinthesky** [comment]
It might be annoying, though, since we'd need to replace all of the glyphicons since they aren't supported anymore in Bootstrap 4, and there would be small syntax changes all over the place. Maybe we could give it a try but I'm not too sure if it would be worth it unless we're planning to overhaul the site design completely...

**Comment by vck3000** [comment]
I haven't had a chance to review Bootstrap 4 unfortunately. It would be nice to have updated code (for example your ES6 changes), but I haven't gotten around to it yet. As you say though, I suspect it would be more than slightly annoying. I tried to make my code as neat as possible, but in certain parts where I lack the deep understanding, I've hacked it together to make it work decently. I worry that I may have some CSS that may be hard to replicate if you're simply trying to adapt my old code! (Although it seems like you've navigated and understood my code well so far to be able to dish out these changes with lightning speed...!)

**Comment by vck3000** [comment]
This actually looks really good. Just some locations to fix up before this can go live:

image
image
image
image
image

**Comment by vck3000** [comment]
#Fixes #209.

**Comment by piguyinthesky** [comment]
Alright, I added a couple of styles for dark mode! I'm not too sure which colours to use for the forum yet.

**Pull request merged**
