### PR TITLE
Implements #173: lets players/specs submit a guess of who Merlin is,

### PR DESCRIPTION
**Pull request by bocaben**
which will be shown publicly in the end.

### CODE REVIEW

**Comment by bocaben** [comment]
wasnt sure about sending the results to someone who left the room. i guess it can be implemented if theres deman for it

**Comment by vck3000** [comment]
Ideally socket.js only passes the guessmerlin request into the game.js file, and the detailed implementation handled within game.js. Right now you have the variable merlinguesses that is shared across two files. Also please add ` {} ` to the if statements to ensure that a similar error like last time doesn't happen again!  

Also should VT be allowed to guess merlin? I personally think only spectators should be allowed to guess merlin... thoughts?

It also looks like when you are posting the result, if there were multiple guesses, then `this.sendText(this.allSockets, "Correct guessers were: " + guessesByTarget[target].join(', '), "server-text");` would be run multiple times? Is this intended?

**Comment by bocaben** [comment]
1) Ok, I can put the logic in the game.js file. Makes sense for socket.js
to be less aware of the inner workings of a game.

2) I think it gives them something to do while waiting to see who gets
shot. Often res are just as interested in guessing as specs, if not more.
Also, by allowing spies to vote too, they can submit an official "protest
vote" if they want to show they would have overridden the assassin's
choice. I should probably block the assassin from guessing though. And
sure, I'll add brackets.

3) I don't think so. Note that I invert the guesses dict. So when I collect
the guess requests, it's {guesser: target}. After I invert it, it's
{target: array of those who guessed him }. And since there is only 1
merlin, that line should only be run once.

**Comment by vck3000** [comment]
1) :D
2) Ok cool, sounds good. 
3) Ah I see, so the for loop only runs once. Cool!

Thanks boca!

**Pull request merged**
